# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'FontingAwesome-ios-0616' do

  pod 'FontAwesomeKit', '~> 2.2.0'
  pod 'CWStatusBarNotification', '~> 2.3.4'


end



